# Generated by Django 5.0.4 on 2024-05-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_catagory_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagory',
            old_name='image_url',
            new_name='image',
        ),
    ]
